Fixed error when using chrome autofill
`Uncaught TypeError: event.getModifierState is not a function`

When using native autofill feature in Chrome, keydown event is raised but event object is missing getModifierState function and causes this error.

Added an additional check on getModifierState.